const fs = require("fs");
const path = require("path");

const SRC_DIR = path.join(__dirname, ".test");

const content = [
  'import { describe, it, expect } from "vitest";',
  'import { render } from "@testing-library/react";',
  'import Home from "../app/page";',
  'import fs from "fs";',
  'import path from "path";',
  '',
  'const SRC = path.resolve(__dirname, "..");',
  '',
  'function countAnims() {',
  '  const c = fs.readFileSync(path.join(SRC, "app", "globals.css"), "utf-8");',
  '  return (c.match(/@keyframes\\s+[\\w-]+/g) || []).length;',
  '}',
  '',
  'function countBackdrop() {',
  '  const c = fs.readFileSync(path.join(SRC, "app", "globals.css"), "utf-8");',
  '  return (c.match(/backdrop-filter/g) || []).length;',
  '}',
  '',
  'function read(file) {',
  '  return fs.readFileSync(path.join(SRC, file), "utf-8");',
  '}',
  '',
  'describe("Graphics - GPU Efficiency", () => {',
  '  it("rainbow cursor canvas sets pointer-events:none and z-index:0", () => {',
  '    const src = read("components/RainbowCursor.tsx");',
  '    expect(src).toContain("pointer-events:none");',
  '    expect(src).toContain("z-index:0");',
  '  });',
  '',
  '  it("main content z-index above canvas", () => {',
  '    const css = read("app/globals.css");',
  '    expect(css).toContain("z-index: 1");',
  '  });',
  '',
  '  it("no WebGL context used (2d canvas only)", () => {',
  '    const avatar = read("components/Avatar.tsx");',
  '    expect(avatar).not.toContain("webgl");',
  '    expect(avatar).toContain(\'getContext("2d")\');',
  '    const cursor = read("components/RainbowCursor.tsx");',
  '    expect(cursor).toContain(\'getContext("2d"\');',
  '    expect(cursor).not.toContain("webgl");',
  '  });',
  '',
  '  it("animation capped at 30fps to reduce GPU load", () => {',
  '    const src = read("components/RainbowCursor.tsx");',
  '    const m = src.match(/FRAME_INTERVAL\\s*=\\s*1000\\s*\\/\\s*(\\d+)/);',
  '    expect(m).toBeTruthy();',
  '    const fps = parseFloat(m[1]);',
  '    expect(fps).toBeLessThanOrEqual(33);',
  '    expect(fps).toBeGreaterThanOrEqual(15);',
  '  });',
  '',
  '  it("trail uses lerping not instant tracking", () => {',
  '    const src = read("components/Avatar.tsx");',
  '    expect(src).toContain("0.12");',
  '  });',
  '',
  '  it("avatar canvas uses clearRect for efficiency", () => {',
  '    const src = read("components/Avatar.tsx");',
  '    expect(src).toContain("clearRect");',
  '  });',
  '',
  '  it("rainbow cursor skips frames below 90% interval", () => {',
  '    const src = read("components/RainbowCursor.tsx");',
  '    expect(src).toContain("FRAME_INTERVAL * 0.9");',
  '  });',
  '});',
  '',
  'describe("Graphics - Fidelity", () => {',
  '  it("avatar has 192 frames for smooth animation", () => {',
  '    const src = read("components/Avatar.tsx");',
  '    expect(src).toMatch(/TOTAL_FRAMES\\s*=\\s*192/);',
  '  });',
  '',
  '  it("frame URL zero-padded (frame_0001.webp)", () => {',
  '    const src = read("components/Avatar.tsx");',
  '    expect(src).toMatch(/padStart\\(4,\\s*"0"\\)/);',
  '  });',
  '',
  '  it("avatar images are webp format", () => {',
  '    const src = read("components/Avatar.tsx");',
  '    expect(src).toContain(".webp");',
  '  });',
  '',
  '  it("avatar respects image natural dimensions", () => {',
  '    const src = read("components/Avatar.tsx");',
  '    expect(src).toContain("img.naturalWidth");',
  '    expect(src).toContain("img.naturalHeight");',
  '  });',
  '',
  '  it("avatar only redraws when dimensions change", () => {',
  '    const src = read("components/Avatar.tsx");',
  '    expect(src).toContain("node.width !== img.naturalWidth");',
  '  });',
  '',
  '  it("rainbow trail has 20 segments", () => {',
  '    const src = read("components/RainbowCursor.tsx");',
  '    expect(src).toMatch(/TRAIL_LENGTH\\s*=\\s*20/);',
  '  });',
  '',
  '  it("rainbow dot base size reasonable (under 300px)", () => {',
  '    const src = read("components/RainbowCursor.tsx");',
  '    const m = src.match(/DOT_BASE_SIZE\\s*=\\s*(\\d+)/);',
  '    expect(m).toBeTruthy();',
  '    expect(parseInt(m[1])).toBeLessThanOrEqual(300);',
  '  });',
  '',
  '  it("rainbow trail opacity uses 0.18 for subtle effect", () => {',
  '    const src = read("components/RainbowCursor.tsx");',
  '    expect(src).toContain("0.18");',
  '  });',
  '',
  '  it("rainbow uses radialGradient for smooth edges", () => {',
  '    const src = read("components/RainbowCursor.tsx");',
  '    expect(src).toContain("createRadialGradient");',
  '  });',
  '',
  '  it("rainbow particles use multi-stop gradients", () => {',
  '    const src = read("components/RainbowCursor.tsx");',
  '    expect(src).toContain("addColorStop(0,");',
  '    expect(src).toContain("addColorStop(0.6,");',
  '    expect(src).toContain("addColorStop(1,");',
  '  });',
  '',
  '  it("pop explosion spawns 28 particles", () => {',
  '    const src = read("components/RainbowCursor.tsx");',
  '    expect(src).toMatch(/POP_PARTICLES\\s*=\\s*28/);',
  '  });',
  '',
  '  it("firework spawns 10 particles", () => {',
  '    const src = read("components/RainbowCursor.tsx");',
  '    expect(src).toMatch(/FIREWORK_PARTICLES\\s*=\\s*10/);',
  '  });',
  '',
  '  it("particles capped at MAX_PARTICLES 150", () => {',
  '    const src = read("components/RainbowCursor.tsx");',
  '    const m = src.match(/MAX_PARTICLES\\s*=\\s*(\\d+)/);',
  '    expect(m).toBeTruthy();',
  '    expect(parseInt(m[1])).toBeLessThanOrEqual(200);',
  '  });',
  '',
  '  it("avatar float uses CSS animation (GPU optimized)", () => {',
  '    const css = read("app/globals.css");',
  '    expect(css).toContain("@keyframes avatar-float");',
  '    expect(css).toContain(".avatar-float");',
  '  });',
  '',
  '  it("avatar glow uses CSS animation", () => {',
  '    const css = read("app/globals.css");',
  '    expect(css).toContain("@keyframes pulse-glow");',
  '  });',
  '',
  '  it("noise overlay uses CSS not canvas", () => {',
  '    const { container } = render(<Home />);',
  '    expect(container.querySelector(".noise-overlay")).toBeTruthy();',
  '    expect(container.querySelector("canvas.noise-overlay")).toBeFalsy();',
  '  });',
  '});',
  '',
  'describe("Graphics - Image Asset Optimization", () => {',
  '  it("avatar frames directory exists", () => {',
  '    const dir = path.join(SRC, "public", "avatar-frames");',
  '    expect(fs.existsSync(dir)).toBe(true);',
  '  });',
  '',
  '  it("frame files follow naming convention (frame_NNNN.webp)", () => {',
  '    const dir = path.join(SRC, "public", "avatar-frames");',
  '    const files = fs.readdirSync(dir);',
  '    const valid = files.filter((f) => /^frame_\\d{4}\\.webp$/.test(f));',
  '    expect(valid.length).toBeGreaterThan(100);',
  '  });',
  '',
  '  it("all frames are webp", () => {',
  '    const dir = path.join(SRC, "public", "avatar-frames");',
  '    const files = fs.readdirSync(dir);',
  '    const webp = files.filter((f) => f.endsWith(".webp"));',
  '    expect(webp.length).toBe(files.length);',
  '  });',
  '',
  '  it("frame count matches TOTAL_FRAMES (192)", () => {',
  '    const dir = path.join(SRC, "public", "avatar-frames");',
  '    const files = fs.readdirSync(dir).filter((f) => f.endsWith(".webp"));',
  '    expect(files.length).toBe(192);',
  '  });',
  '',
  '  it("project images use Next.js Image with fill", () => {',
  '    const src = read("components/ProjectsShowcase.tsx");',
  '    expect(src).toContain("fill");',
  '  });',
  '',
  '  it("frame files avg under 30KB for fast load", () => {',
  '    const dir = path.join(SRC, "public", "avatar-frames");',
  '    const files = fs.readdirSync(dir).filter((f) => f.endsWith(".webp"));',
  '    let total = 0;',
  '    let oversize = 0;',
  '    files.forEach((f) => {',
  '      const sz = fs.statSync(path.join(dir, f)).size;',
  '      total += sz;',
  '      if (sz > 50 * 1024) oversize++;',
  '    });',
  '    expect(total / files.length).toBeLessThan(30 * 1024);',
  '    expect(oversize).toBeLessThanOrEqual(5);',
  '  });',
  '});',
  '',
  'describe("Graphics - Render Budget", () => {',
  '  it("CSS animations under 10 total", () => {',
  '    expect(countAnims()).toBeLessThan(10);',
  '  });',
  '',
  '  it("backdrop-filter usage under 10 total", () => {',
  '    expect(countBackdrop()).toBeLessThan(10);',
  '  });',
  '',
  '  it("no more than 2 canvas elements in DOM", () => {',
  '    const { container, unmount } = render(<Home />);',
  '    expect(container.querySelectorAll("canvas").length).toBeLessThanOrEqual(2);',
  '    unmount();',
  '  });',
  '});',
].join("\n");

const target = path.join(__dirname, ".test", "graphics.test.jsx");
fs.writeFileSync(target, content);
console.log("Written " + content.length + " chars to " + target);
